---
  - hosts: all
    remote_user: root
    tasks:
    - name: Install docker
      apt: pkg={{item}} state=installed install_recommends=no update_cache=yes
      with_items:
        - docker.io
    - name: Install openvpn
      apt: pkg=openvpn state=installed install_recommends=no
    - name: Install java (TeamCity agent requirement)
      apt: pkg=openjdk-8-jre-headless state=installed install_recommends=no
    - name: Install unzip (TeamCity agent requirements)
      apt: pkg=unzip state=installed install_recommends=no

