  - name: Install bitbake dependencies for pelux image
    apt: name={{item}} state=installed install_recommends=no
    with_items:
    - git
    - sed
    - wget
    - cvs
    - subversion
    - git-core
    - coreutils
    - unzip
    - gawk
    - python-pysqlite2
    - diffstat
    - help2man
    - make
    - gcc
    - build-essential
    - g++
    - chrpath
    - libxml2-utils
    - libsdl1.2-dev
    - texinfo
    - python3
    - gcc-multilib
    - g++-multilib
