  - name: Install software factory dependecies
    apt: name={{item}} state=installed install_recommends=no
    with_items:
    - cmake
    - make
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - aspell
    - aspell-en
    - python-sphinx
    - python-sphinx-rtd-theme
    - python-sphinxcontrib.seqdiag
    - python-sphinxcontrib.blockdiag
    - python-sphinxcontrib.actdiag
  - name: Pip install sphinx
    pip: virtualenv=/home/allview/virtualenv virtualenv_site_packages=yes name={{item}}
    become_user: allview
    become: yes
    with_items:
    - sphinxcontrib-seqdiag
    - sphinxcontrib-blockdiag
    - sphinxcontrib-actdiag
    - sphinxcontrib-manpage
    - sphinx_rtd_theme

