  - name: Install software factory dependecies
    apt: name={{item}} state=installed install_recommends=no
    with_items:
    - cmake
    - make
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - aspell
    - aspell-en
    - python-sphinx
    - python-sphinx-rtd-theme
    - python-sphinxcontrib.seqdiag
    - python-sphinxcontrib.blockdiag
    - python-sphinxcontrib.actdiag
