  - name: Install bitbake dependencies for pelux image
    apt: name={{item}} state=installed install_recommends=no
    with_items:
    - git
    - sed
    - wget
    - cvs
    - subversion
    - git-core
    - coreutils
    - unzip
    - gawk
    - python-pysqlite2
    - diffstat
    - help2man
    - make
    - gcc
    - build-essential
    - g++
    - chrpath
    - libxml2-utils
    - libsdl1.2-dev
    - texinfo
    - python3
    - gcc-multilib
    - g++-multilib
  - name: Install autofs for nfs access
    apt: name=autofs state=installed
    register: autofs1
  - name: Change autofs settings to allow nfs automount
    register: autofs2
    lineinfile:
      state: present
      dest: /etc/auto.master
      regexp: '^/net '
      insertafter: '^#/net '
      line: '/net /etc/auto.net'
  - name: restart autofs on change
    service: state=restarted name=autofs
    when: autofs1.changed or autofs2.changed
  - name: make symlinks
    become: yes
    become_user: allview
    file:
      state: link 
      src: '/net/192.168.5.1/home/nfsexports/{{ item.src }}'
      dest: '/home/allview/{{ item.dest }}'
    with_items:
    - { src: 'bitbake_downloads', dest: 'bitbake_downloads' }
    - { src: 'bitbake_repo', dest: 'bitbake_repo' }
    - { src: 'bitbake_sstate', dest: 'bitbake_sstate' }
    - { src: 'vagrant_caches', dest: 'vagrant_caches' }
  - name: Fetch keys
    get_url:
      url: 'http://10.9.0.1/share/keys/ssh.tar'
      dest: /var/lib/ansible/ssh.tar
      mode: 0444
  - name: Unpack ssh keys
    become: yes
    become_user: allview
    unarchive:
      src: /var/lib/ansible/ssh.tar
      dest: /home/allview/
      remote_src: yes
